# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sunrise-feedbacks}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Igor Galeta", "Pavlo Galeta"]
  s.date = %q{2011-07-20}
  s.description = %q{Sunrise is a Aimbulance CMS}
  s.email = %q{galeta.igor@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
    "Rakefile",
    "app/controllers/feedbacks_controller.rb",
    "app/controllers/manage/feedbacks_controller.rb",
    "app/helpers/manage/feedbacks_helper.rb",
    "app/views/feedbacks/_form.html.erb",
    "app/views/feedbacks/new.html.erb",
    "app/views/manage/feedbacks/_answer.html.erb",
    "app/views/manage/feedbacks/_feedback.html.erb",
    "app/views/manage/feedbacks/_form.html.erb",
    "app/views/manage/feedbacks/_message.html.erb",
    "app/views/manage/feedbacks/_model_filter.html.erb",
    "app/views/manage/feedbacks/edit.html.erb",
    "app/views/manage/feedbacks/index.html.erb",
    "app/views/manage/feedbacks/new.html.erb",
    "app/views/manage/feedbacks/show.html.erb",
    "config/locales/ru.yml",
    "config/locales/uk.yml",
    "config/routes.rb",
    "lib/generators/sunrise/feedbacks/USAGE",
    "lib/generators/sunrise/feedbacks/install_generator.rb",
    "lib/generators/sunrise/feedbacks/templates/create_feedback_answers.rb",
    "lib/generators/sunrise/feedbacks/templates/create_feedback_messages.rb",
    "lib/generators/sunrise/feedbacks/templates/feedback_answer.rb",
    "lib/generators/sunrise/feedbacks/templates/feedback_message.rb",
    "lib/sunrise-feedbacks.rb",
    "lib/sunrise/feedbacks.rb",
    "lib/sunrise/feedbacks/author.rb",
    "lib/sunrise/feedbacks/engine.rb",
    "lib/sunrise/feedbacks/version.rb",
    "lib/sunrise/models/feedback_answer.rb",
    "lib/sunrise/models/feedback_message.rb"
  ]
  s.homepage = %q{https://github.com/galetahub/sunrise-feedbacks}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Rails CMS}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sunrise-cms>, [">= 0"])
    else
      s.add_dependency(%q<sunrise-cms>, [">= 0"])
    end
  else
    s.add_dependency(%q<sunrise-cms>, [">= 0"])
  end
end

